### PR TITLE
Update getimagedata.js

### PR DESCRIPTION
**Pull request by andre161292**
Using a 32-Bit typed array, the iteration and access to the array is way faster. 
To access the values, you have to shift the values by it's 32-8-bit-relative position, as following:

red = data[0] & 0xFF
green = data[0] >> 8 & 0xFF
blue = data[0] >> 16 & 0xFF
alpha = data[0] >> 24 & 0xFF

### CODE REVIEW

**Comment by dysphasia** [comment]
Thanks! When I have some extra time I'd like to run benchmarks on the two different methods. I remember trying something similar before and discovering it was slower.

**Comment by jennschiffer** [comment]
Wait, you are merging _before_ running benchmarks?

**Comment by dysphasia** [comment]
I believe him, yo. I don't know why but I do.

**Comment by jennschiffer** [comment]
Because his avatar is a dog taking a piss :santa:

**Pull request merged**
